version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:18.04-5.2
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.2"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:18.04-5.2

  integration-tests:
    image: swift-nio-http2:18.04-5.2
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=52000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=51000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=333000
      - MAX_ALLOCS_ALLOWED_client_server_request_response=296000
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=55000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=354000

  performance-test:
    image: swift-nio-http2:18.04-5.2

  h2spec:
    image: swift-nio-http2:18.04-5.2

  test:
    image: swift-nio-http2:18.04-5.2
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=52000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=51000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=333000
      - MAX_ALLOCS_ALLOWED_client_server_request_response=296000
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=55000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=354000

  shell:
    image: swift-nio-http2:18.04-5.2
