version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:22.04-5.8

  integration-tests:
    image: swift-nio-http2:22.04-5.8

  performance-test:
    image: swift-nio-http2:22.04-5.8

  h2spec:
    image: swift-nio-http2:22.04-5.8

  documentation-check:
    image: swift-nio-http2:22.04-5.8

  test:
    image: swift-nio-http2:22.04-5.8
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_inline_interleaved=35150
      - MAX_ALLOCS_ALLOWED_1k_requests_inline_noninterleaved=34100
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=41150
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=40100
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=288050
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response_inline=265050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=257050
      - MAX_ALLOCS_ALLOWED_client_server_request_response_inline=240050
      - MAX_ALLOCS_ALLOWED_client_server_request_response_many=1202050
      - MAX_ALLOCS_ALLOWED_client_server_request_response_many_inline=885050
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=33050
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel_inline=33050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form=200050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace=200050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_long_string=300050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_short_string=200050
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=292950
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent_inline=291650
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  shell:
    image: swift-nio-http2:22.04-5.8
