version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:16.04-5.1
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.1"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:16.04-5.1

  integration-tests:
    image: swift-nio-http2:16.04-5.1
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=53000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=52000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=336000
      - MAX_ALLOCS_ALLOWED_client_server_request_response=300000
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=55000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=354000

  performance-test:
    image: swift-nio-http2:16.04-5.1

  h2spec:
    image: swift-nio-http2:16.04-5.1

  test:
    image: swift-nio-http2:16.04-5.1
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=53000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=52000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=336000
      - MAX_ALLOCS_ALLOWED_client_server_request_response=300000
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=55000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=354000
      - SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-nio-http2:16.04-5.1
